url: http://friendsfromjg.github.io
baseurl: /

# Site Settings
title: Friends from JG
description: "강릉고 주문진 38기 친구들의 모임"
keywords: "강릉고, theme"

google-tracking-id:
# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
